; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	g:\Max\Bastelstube\FL\FLHook Source\flhookplugin_MoD\plugins\playercntl_plugin\src\PlayerInfo.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?_Value@?$_Is_swap_move@U_Swap_move_tag@std@@@std@@2_NB ; std::_Is_swap_move<std::_Swap_move_tag>::_Value
PUBLIC	?collate@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::collate
PUBLIC	?ctype@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::ctype
PUBLIC	?monetary@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::monetary
PUBLIC	?numeric@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::numeric
PUBLIC	?time@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::time
PUBLIC	?messages@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::messages
PUBLIC	?all@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::all
PUBLIC	?none@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::none
PUBLIC	?skipws@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::skipws
PUBLIC	?unitbuf@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::unitbuf
PUBLIC	?uppercase@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::uppercase
PUBLIC	?showbase@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::showbase
PUBLIC	?showpoint@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::showpoint
PUBLIC	?showpos@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::showpos
PUBLIC	?left@?$_Iosb@H@std@@2W4_Fmtflags@12@B		; std::_Iosb<int>::left
PUBLIC	?right@?$_Iosb@H@std@@2W4_Fmtflags@12@B		; std::_Iosb<int>::right
PUBLIC	?internal@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::internal
PUBLIC	?dec@?$_Iosb@H@std@@2W4_Fmtflags@12@B		; std::_Iosb<int>::dec
PUBLIC	?oct@?$_Iosb@H@std@@2W4_Fmtflags@12@B		; std::_Iosb<int>::oct
PUBLIC	?hex@?$_Iosb@H@std@@2W4_Fmtflags@12@B		; std::_Iosb<int>::hex
PUBLIC	?scientific@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::scientific
PUBLIC	?fixed@?$_Iosb@H@std@@2W4_Fmtflags@12@B		; std::_Iosb<int>::fixed
PUBLIC	?hexfloat@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::hexfloat
PUBLIC	?boolalpha@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::boolalpha
PUBLIC	?_Stdio@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::_Stdio
PUBLIC	?adjustfield@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::adjustfield
PUBLIC	?basefield@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::basefield
PUBLIC	?floatfield@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::floatfield
PUBLIC	?goodbit@?$_Iosb@H@std@@2W4_Iostate@12@B	; std::_Iosb<int>::goodbit
PUBLIC	?eofbit@?$_Iosb@H@std@@2W4_Iostate@12@B		; std::_Iosb<int>::eofbit
PUBLIC	?failbit@?$_Iosb@H@std@@2W4_Iostate@12@B	; std::_Iosb<int>::failbit
PUBLIC	?badbit@?$_Iosb@H@std@@2W4_Iostate@12@B		; std::_Iosb<int>::badbit
PUBLIC	?_Hardfail@?$_Iosb@H@std@@2W4_Iostate@12@B	; std::_Iosb<int>::_Hardfail
PUBLIC	?in@?$_Iosb@H@std@@2W4_Openmode@12@B		; std::_Iosb<int>::in
PUBLIC	?out@?$_Iosb@H@std@@2W4_Openmode@12@B		; std::_Iosb<int>::out
PUBLIC	?ate@?$_Iosb@H@std@@2W4_Openmode@12@B		; std::_Iosb<int>::ate
PUBLIC	?app@?$_Iosb@H@std@@2W4_Openmode@12@B		; std::_Iosb<int>::app
PUBLIC	?trunc@?$_Iosb@H@std@@2W4_Openmode@12@B		; std::_Iosb<int>::trunc
PUBLIC	?_Nocreate@?$_Iosb@H@std@@2W4_Openmode@12@B	; std::_Iosb<int>::_Nocreate
PUBLIC	?_Noreplace@?$_Iosb@H@std@@2W4_Openmode@12@B	; std::_Iosb<int>::_Noreplace
PUBLIC	?binary@?$_Iosb@H@std@@2W4_Openmode@12@B	; std::_Iosb<int>::binary
PUBLIC	?beg@?$_Iosb@H@std@@2W4_Seekdir@12@B		; std::_Iosb<int>::beg
PUBLIC	?cur@?$_Iosb@H@std@@2W4_Seekdir@12@B		; std::_Iosb<int>::cur
PUBLIC	?end@?$_Iosb@H@std@@2W4_Seekdir@12@B		; std::_Iosb<int>::end
PUBLIC	?value@?$integral_constant@_N$0A@@tr1@std@@2_NB	; std::tr1::integral_constant<bool,0>::value
PUBLIC	?value@?$integral_constant@_N$00@tr1@std@@2_NB	; std::tr1::integral_constant<bool,1>::value
;	COMDAT ?value@?$integral_constant@_N$00@tr1@std@@2_NB
CONST	SEGMENT
?value@?$integral_constant@_N$00@tr1@std@@2_NB DB 01H	; std::tr1::integral_constant<bool,1>::value
CONST	ENDS
;	COMDAT ?value@?$integral_constant@_N$0A@@tr1@std@@2_NB
CONST	SEGMENT
?value@?$integral_constant@_N$0A@@tr1@std@@2_NB DB 00H	; std::tr1::integral_constant<bool,0>::value
CONST	ENDS
;	COMDAT ?end@?$_Iosb@H@std@@2W4_Seekdir@12@B
CONST	SEGMENT
?end@?$_Iosb@H@std@@2W4_Seekdir@12@B DD 02H		; std::_Iosb<int>::end
CONST	ENDS
;	COMDAT ?cur@?$_Iosb@H@std@@2W4_Seekdir@12@B
CONST	SEGMENT
?cur@?$_Iosb@H@std@@2W4_Seekdir@12@B DD 01H		; std::_Iosb<int>::cur
CONST	ENDS
;	COMDAT ?beg@?$_Iosb@H@std@@2W4_Seekdir@12@B
CONST	SEGMENT
?beg@?$_Iosb@H@std@@2W4_Seekdir@12@B DD 00H		; std::_Iosb<int>::beg
CONST	ENDS
;	COMDAT ?binary@?$_Iosb@H@std@@2W4_Openmode@12@B
CONST	SEGMENT
?binary@?$_Iosb@H@std@@2W4_Openmode@12@B DD 020H	; std::_Iosb<int>::binary
CONST	ENDS
;	COMDAT ?_Noreplace@?$_Iosb@H@std@@2W4_Openmode@12@B
CONST	SEGMENT
?_Noreplace@?$_Iosb@H@std@@2W4_Openmode@12@B DD 080H	; std::_Iosb<int>::_Noreplace
CONST	ENDS
;	COMDAT ?_Nocreate@?$_Iosb@H@std@@2W4_Openmode@12@B
CONST	SEGMENT
?_Nocreate@?$_Iosb@H@std@@2W4_Openmode@12@B DD 040H	; std::_Iosb<int>::_Nocreate
CONST	ENDS
;	COMDAT ?trunc@?$_Iosb@H@std@@2W4_Openmode@12@B
CONST	SEGMENT
?trunc@?$_Iosb@H@std@@2W4_Openmode@12@B DD 010H		; std::_Iosb<int>::trunc
CONST	ENDS
;	COMDAT ?app@?$_Iosb@H@std@@2W4_Openmode@12@B
CONST	SEGMENT
?app@?$_Iosb@H@std@@2W4_Openmode@12@B DD 08H		; std::_Iosb<int>::app
CONST	ENDS
;	COMDAT ?ate@?$_Iosb@H@std@@2W4_Openmode@12@B
CONST	SEGMENT
?ate@?$_Iosb@H@std@@2W4_Openmode@12@B DD 04H		; std::_Iosb<int>::ate
CONST	ENDS
;	COMDAT ?out@?$_Iosb@H@std@@2W4_Openmode@12@B
CONST	SEGMENT
?out@?$_Iosb@H@std@@2W4_Openmode@12@B DD 02H		; std::_Iosb<int>::out
CONST	ENDS
;	COMDAT ?in@?$_Iosb@H@std@@2W4_Openmode@12@B
CONST	SEGMENT
?in@?$_Iosb@H@std@@2W4_Openmode@12@B DD 01H		; std::_Iosb<int>::in
CONST	ENDS
;	COMDAT ?_Hardfail@?$_Iosb@H@std@@2W4_Iostate@12@B
CONST	SEGMENT
?_Hardfail@?$_Iosb@H@std@@2W4_Iostate@12@B DD 010H	; std::_Iosb<int>::_Hardfail
CONST	ENDS
;	COMDAT ?badbit@?$_Iosb@H@std@@2W4_Iostate@12@B
CONST	SEGMENT
?badbit@?$_Iosb@H@std@@2W4_Iostate@12@B DD 04H		; std::_Iosb<int>::badbit
CONST	ENDS
;	COMDAT ?failbit@?$_Iosb@H@std@@2W4_Iostate@12@B
CONST	SEGMENT
?failbit@?$_Iosb@H@std@@2W4_Iostate@12@B DD 02H		; std::_Iosb<int>::failbit
CONST	ENDS
;	COMDAT ?eofbit@?$_Iosb@H@std@@2W4_Iostate@12@B
CONST	SEGMENT
?eofbit@?$_Iosb@H@std@@2W4_Iostate@12@B DD 01H		; std::_Iosb<int>::eofbit
CONST	ENDS
;	COMDAT ?goodbit@?$_Iosb@H@std@@2W4_Iostate@12@B
CONST	SEGMENT
?goodbit@?$_Iosb@H@std@@2W4_Iostate@12@B DD 00H		; std::_Iosb<int>::goodbit
CONST	ENDS
;	COMDAT ?floatfield@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?floatfield@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 03000H	; std::_Iosb<int>::floatfield
CONST	ENDS
;	COMDAT ?basefield@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?basefield@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 0e00H	; std::_Iosb<int>::basefield
CONST	ENDS
;	COMDAT ?adjustfield@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?adjustfield@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 01c0H	; std::_Iosb<int>::adjustfield
CONST	ENDS
;	COMDAT ?_Stdio@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?_Stdio@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 08000H	; std::_Iosb<int>::_Stdio
CONST	ENDS
;	COMDAT ?boolalpha@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?boolalpha@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 04000H	; std::_Iosb<int>::boolalpha
CONST	ENDS
;	COMDAT ?hexfloat@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?hexfloat@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 03000H	; std::_Iosb<int>::hexfloat
CONST	ENDS
;	COMDAT ?fixed@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?fixed@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 02000H	; std::_Iosb<int>::fixed
CONST	ENDS
;	COMDAT ?scientific@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?scientific@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 01000H	; std::_Iosb<int>::scientific
CONST	ENDS
;	COMDAT ?hex@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?hex@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 0800H		; std::_Iosb<int>::hex
CONST	ENDS
;	COMDAT ?oct@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?oct@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 0400H		; std::_Iosb<int>::oct
CONST	ENDS
;	COMDAT ?dec@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?dec@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 0200H		; std::_Iosb<int>::dec
CONST	ENDS
;	COMDAT ?internal@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?internal@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 0100H	; std::_Iosb<int>::internal
CONST	ENDS
;	COMDAT ?right@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?right@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 080H		; std::_Iosb<int>::right
CONST	ENDS
;	COMDAT ?left@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?left@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 040H		; std::_Iosb<int>::left
CONST	ENDS
;	COMDAT ?showpos@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?showpos@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 020H	; std::_Iosb<int>::showpos
CONST	ENDS
;	COMDAT ?showpoint@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?showpoint@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 010H	; std::_Iosb<int>::showpoint
CONST	ENDS
;	COMDAT ?showbase@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?showbase@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 08H	; std::_Iosb<int>::showbase
CONST	ENDS
;	COMDAT ?uppercase@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?uppercase@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 04H	; std::_Iosb<int>::uppercase
CONST	ENDS
;	COMDAT ?unitbuf@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?unitbuf@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 02H	; std::_Iosb<int>::unitbuf
CONST	ENDS
;	COMDAT ?skipws@?$_Iosb@H@std@@2W4_Fmtflags@12@B
CONST	SEGMENT
?skipws@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 01H		; std::_Iosb<int>::skipws
CONST	ENDS
;	COMDAT ?none@?$_Locbase@H@std@@2HB
CONST	SEGMENT
?none@?$_Locbase@H@std@@2HB DD 00H			; std::_Locbase<int>::none
CONST	ENDS
;	COMDAT ?all@?$_Locbase@H@std@@2HB
CONST	SEGMENT
?all@?$_Locbase@H@std@@2HB DD 03fH			; std::_Locbase<int>::all
CONST	ENDS
;	COMDAT ?messages@?$_Locbase@H@std@@2HB
CONST	SEGMENT
?messages@?$_Locbase@H@std@@2HB DD 020H			; std::_Locbase<int>::messages
CONST	ENDS
;	COMDAT ?time@?$_Locbase@H@std@@2HB
CONST	SEGMENT
?time@?$_Locbase@H@std@@2HB DD 010H			; std::_Locbase<int>::time
CONST	ENDS
;	COMDAT ?numeric@?$_Locbase@H@std@@2HB
CONST	SEGMENT
?numeric@?$_Locbase@H@std@@2HB DD 08H			; std::_Locbase<int>::numeric
CONST	ENDS
;	COMDAT ?monetary@?$_Locbase@H@std@@2HB
CONST	SEGMENT
?monetary@?$_Locbase@H@std@@2HB DD 04H			; std::_Locbase<int>::monetary
CONST	ENDS
;	COMDAT ?ctype@?$_Locbase@H@std@@2HB
CONST	SEGMENT
?ctype@?$_Locbase@H@std@@2HB DD 02H			; std::_Locbase<int>::ctype
CONST	ENDS
;	COMDAT ?collate@?$_Locbase@H@std@@2HB
CONST	SEGMENT
?collate@?$_Locbase@H@std@@2HB DD 01H			; std::_Locbase<int>::collate
CONST	ENDS
;	COMDAT ?_Value@?$_Is_swap_move@U_Swap_move_tag@std@@@std@@2_NB
CONST	SEGMENT
?_Value@?$_Is_swap_move@U_Swap_move_tag@std@@@std@@2_NB DB 01H ; std::_Is_swap_move<std::_Swap_move_tag>::_Value
CONST	ENDS
_DATA	SEGMENT
__bad_alloc_Message DD FLAT:$SG63979
_DATA	ENDS
CONST	SEGMENT
$SG63979 DB	'bad allocation', 00H
$SG139067 DB	00H
$SG139071 DB	00H, 00H
	ORG $+2
$SG139077 DB	'%02X%02X', 00H
	ORG $+3
$SG139182 DB	'm', 00H, 'e', 00H, 00H, 00H
	ORG $+2
$SG139190 DB	'E', 00H, 'R', 00H, 'R', 00H, ' ', 00H, 'N', 00H, 'o', 00H
	DB	' ', 00H, 't', 00H, 'a', 00H, 'r', 00H, 'g', 00H, 'e', 00H, 't'
	DB	00H, 00H, 00H
$SG139196 DB	'-info.ini', 00H
	ORG $+2
$SG139198 DB	'<', 00H, 'R', 00H, 'D', 00H, 'L', 00H, '>', 00H, '<', 00H
	DB	'P', 00H, 'U', 00H, 'S', 00H, 'H', 00H, '/', 00H, '>', 00H, 00H
	DB	00H
	ORG $+2
$SG139208 DB	00H, 00H
	ORG $+2
$SG139209 DB	'Info', 00H
	ORG $+3
$SG139213 DB	'<', 00H, '/', 00H, 'T', 00H, 'E', 00H, 'X', 00H, 'T', 00H
	DB	'>', 00H, '<', 00H, 'P', 00H, 'A', 00H, 'R', 00H, 'A', 00H, '/'
	DB	00H, '>', 00H, '<', 00H, 'P', 00H, 'A', 00H, 'R', 00H, 'A', 00H
	DB	'/', 00H, '>', 00H, 00H, 00H
$SG139214 DB	'<', 00H, 'T', 00H, 'E', 00H, 'X', 00H, 'T', 00H, '>', 00H
	DB	00H, 00H
	ORG $+2
$SG139220 DB	00H, 00H
	ORG $+2
$SG139221 DB	'AdminNote', 00H
	ORG $+2
$SG139222 DB	'Info', 00H
	ORG $+3
$SG139226 DB	'<', 00H, '/', 00H, 'T', 00H, 'E', 00H, 'X', 00H, 'T', 00H
	DB	'>', 00H, '<', 00H, 'P', 00H, 'A', 00H, 'R', 00H, 'A', 00H, '/'
	DB	00H, '>', 00H, '<', 00H, 'P', 00H, 'A', 00H, 'R', 00H, 'A', 00H
	DB	'/', 00H, '>', 00H, 00H, 00H
$SG139227 DB	'<', 00H, 'T', 00H, 'E', 00H, 'X', 00H, 'T', 00H, '>', 00H
	DB	00H, 00H
	ORG $+2
$SG139228 DB	'<', 00H, 'P', 00H, 'O', 00H, 'P', 00H, '/', 00H, '>', 00H
	DB	'<', 00H, '/', 00H, 'R', 00H, 'D', 00H, 'L', 00H, '>', 00H, 00H
	DB	00H
	ORG $+2
$SG139231 DB	'E', 00H, 'R', 00H, 'R', 00H, ' ', 00H, 'N', 00H, 'o', 00H
	DB	' ', 00H, 'i', 00H, 'n', 00H, 'f', 00H, 'o', 00H, 'r', 00H, 'm'
	DB	00H, 'a', 00H, 't', 00H, 'i', 00H, 'o', 00H, 'n', 00H, ' ', 00H
	DB	'a', 00H, 'v', 00H, 'a', 00H, 'i', 00H, 'l', 00H, 'a', 00H, 'b'
	DB	00H, 'l', 00H, 'e', 00H, 00H, 00H
	ORG $+2
$SG139249 DB	00H, 00H
	ORG $+2
$SG139250 DB	'Info', 00H
	ORG $+3
$SG139269 DB	'-info.ini', 00H
	ORG $+2
$SG139273 DB	'a', 00H, 00H, 00H
$SG139286 DB	00H, 00H
	ORG $+2
$SG139277 DB	'E', 00H, 'R', 00H, 'R', 00H, ' ', 00H, 'T', 00H, 'o', 00H
	DB	'o', 00H, ' ', 00H, 'm', 00H, 'a', 00H, 'n', 00H, 'y', 00H, ' '
	DB	00H, 'c', 00H, 'h', 00H, 'a', 00H, 'r', 00H, 'a', 00H, 'c', 00H
	DB	't', 00H, 'e', 00H, 'r', 00H, 's', 00H, '.', 00H, ' ', 00H, 'L'
	DB	00H, 'i', 00H, 'm', 00H, 'i', 00H, 't', 00H, ' ', 00H, 'i', 00H
	DB	's', 00H, ' ', 00H, '%', 00H, 'd', 00H, 00H, 00H
	ORG $+2
$SG139287 DB	'Info', 00H
	ORG $+3
$SG139290 DB	'Info', 00H
	ORG $+3
$SG139292 DB	'O', 00H, 'K', 00H, ' ', 00H, '%', 00H, 'd', 00H, '/', 00H
	DB	'%', 00H, 'd', 00H, ' ', 00H, 'c', 00H, 'h', 00H, 'a', 00H, 'r'
	DB	00H, 'a', 00H, 'c', 00H, 't', 00H, 'e', 00H, 'r', 00H, 's', 00H
	DB	' ', 00H, 'u', 00H, 's', 00H, 'e', 00H, 'd', 00H, 00H, 00H
	ORG $+2
$SG139295 DB	'd', 00H, 00H, 00H
$SG139299 DB	00H, 00H
	ORG $+2
$SG139300 DB	'Info', 00H
	ORG $+3
$SG139302 DB	'O', 00H, 'K', 00H, 00H, 00H
	ORG $+2
$SG139305 DB	'E', 00H, 'R', 00H, 'R', 00H, ' ', 00H, 'I', 00H, 'n', 00H
	DB	'v', 00H, 'a', 00H, 'l', 00H, 'i', 00H, 'd', 00H, ' ', 00H, 'p'
	DB	00H, 'a', 00H, 'r', 00H, 'a', 00H, 'm', 00H, 'e', 00H, 't', 00H
	DB	'e', 00H, 'r', 00H, 's', 00H, 00H, 00H
	ORG $+2
$SG139307 DB	'/', 00H, 's', 00H, 'e', 00H, 't', 00H, 'i', 00H, 'n', 00H
	DB	'f', 00H, 'o', 00H, ' ', 00H, '<', 00H, 'p', 00H, 'a', 00H, 'r'
	DB	00H, 'a', 00H, 'g', 00H, 'r', 00H, 'a', 00H, 'p', 00H, 'h', 00H
	DB	'>', 00H, ' ', 00H, '<', 00H, 'c', 00H, 'o', 00H, 'm', 00H, 'm'
	DB	00H, 'a', 00H, 'n', 00H, 'd', 00H, '>', 00H, ' ', 00H, '<', 00H
	DB	't', 00H, 'e', 00H, 'x', 00H, 't', 00H, '>', 00H, 00H, 00H
	ORG $+4
$SG139309 DB	'|', 00H, ' ', 00H, ' ', 00H, '<', 00H, 'p', 00H, 'a', 00H
	DB	'r', 00H, 'a', 00H, 'g', 00H, 'r', 00H, 'a', 00H, 'p', 00H, 'h'
	DB	00H, '>', 00H, ' ', 00H, 'T', 00H, 'h', 00H, 'e', 00H, ' ', 00H
	DB	'p', 00H, 'a', 00H, 'r', 00H, 'a', 00H, 'g', 00H, 'r', 00H, 'a'
	DB	00H, 'p', 00H, 'h', 00H, ' ', 00H, 'n', 00H, 'u', 00H, 'm', 00H
	DB	'b', 00H, 'e', 00H, 'r', 00H, ' ', 00H, 'i', 00H, 'n', 00H, ' '
	DB	00H, 't', 00H, 'h', 00H, 'e', 00H, ' ', 00H, 'r', 00H, 'a', 00H
	DB	'n', 00H, 'g', 00H, 'e', 00H, ' ', 00H, '1', 00H, '-', 00H, '%'
	DB	00H, 'd', 00H, 00H, 00H
	ORG $+4
$SG139311 DB	'|', 00H, ' ', 00H, ' ', 00H, '<', 00H, 'c', 00H, 'o', 00H
	DB	'm', 00H, 'm', 00H, 'a', 00H, 'n', 00H, 'd', 00H, '>', 00H, ' '
	DB	00H, 'T', 00H, 'h', 00H, 'e', 00H, ' ', 00H, 'c', 00H, 'o', 00H
	DB	'm', 00H, 'm', 00H, 'a', 00H, 'n', 00H, 'd', 00H, ' ', 00H, 't'
	DB	00H, 'o', 00H, ' ', 00H, 'p', 00H, 'e', 00H, 'r', 00H, 'f', 00H
	DB	'o', 00H, 'r', 00H, 'm', 00H, ' ', 00H, 'o', 00H, 'n', 00H, ' '
	DB	00H, 't', 00H, 'h', 00H, 'e', 00H, ' ', 00H, 'p', 00H, 'a', 00H
	DB	'r', 00H, 'a', 00H, 'g', 00H, 'r', 00H, 'a', 00H, 'p', 00H, 'h'
	DB	00H, ',', 00H, ' ', 00H, '''', 00H, 'a', 00H, '''', 00H, ' ', 00H
	DB	'f', 00H, 'o', 00H, 'r', 00H, ' ', 00H, 'a', 00H, 'p', 00H, 'p'
	DB	00H, 'e', 00H, 'n', 00H, 'd', 00H, ',', 00H, ' ', 00H, '''', 00H
	DB	'd', 00H, '''', 00H, ' ', 00H, 'f', 00H, 'o', 00H, 'r', 00H, ' '
	DB	00H, 'd', 00H, 'e', 00H, 'l', 00H, 'e', 00H, 't', 00H, 'e', 00H
	DB	00H, 00H
CONST	ENDS
PUBLIC	__$ArrayPad$
PUBLIC	?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z ; PlayerInfo::UserCmd_ShowInfo
EXTRN	__imp_??1FmtStr@@QAE@XZ:PROC
EXTRN	__imp_?PopUpDialog@Player@pub@@YAHIABUFmtStr@@0I@Z:PROC
EXTRN	__imp_?end_mad_lib@FmtStr@@QAEXXZ:PROC
EXTRN	__imp_?begin_mad_lib@FmtStr@@QAEXI@Z:PROC
EXTRN	__imp_??0FmtStr@@QAE@IPBUVal@0@@Z:PROC
EXTRN	?HkChangeIDSString@@YAXIIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z:PROC ; HkChangeIDSString
EXTRN	__imp_??Y?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAEAAV01@PBG@Z:PROC
EXTRN	__imp_??Y?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAEAAV01@ABV01@@Z:PROC
EXTRN	__imp_??$?HGU?$char_traits@G@std@@V?$allocator@G@1@@std@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@0@ABV10@PBG@Z:PROC
EXTRN	__imp_??$?HGU?$char_traits@G@std@@V?$allocator@G@1@@std@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@0@PBGABV10@@Z:PROC
EXTRN	__imp_?length@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QBEIXZ:PROC
EXTRN	__imp_?itos@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z:PROC
EXTRN	__imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ:PROC
EXTRN	?GetUserFilePath@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@2@ABV12@@Z:PROC ; GetUserFilePath
EXTRN	__imp_??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@PBD@Z:PROC
EXTRN	__imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ:PROC
EXTRN	__imp_?PrintUserCmdText@@YAXIV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ZZ:PROC
EXTRN	__imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z:PROC
EXTRN	__imp_?HkIsValidClientID@@YA_NI@Z:PROC
EXTRN	__imp_?HkGetClientIDByShip@@YAII@Z:PROC
EXTRN	__imp_?GetTarget@SpaceObj@pub@@YAHABIAAI@Z:PROC
EXTRN	__imp_?GetShip@Player@pub@@YAHABIAAI@Z:PROC
EXTRN	__imp_?GetActiveCharacterName@PlayerDB@@QBEPBGI@Z:PROC
EXTRN	__imp_?Players@@3VPlayerDB@@A:BYTE
EXTRN	__imp_??$?8GU?$char_traits@G@std@@V?$allocator@G@1@@std@@YA_NABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@0@PBG@Z:PROC
EXTRN	__imp_?GetParam@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV12@GI@Z:PROC
EXTRN	___security_cookie:DWORD
EXTRN	___CxxFrameHandler3:PROC
EXTRN	@__security_check_cookie@4:PROC
xdata$x	SEGMENT
__ehfuncinfo$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z DD 019930522H
	DD	01eH
	DD	FLAT:__unwindtable$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	00H
__unwindtable$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$0
	DD	00H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$1
	DD	00H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$2
	DD	02H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$3
	DD	03H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$4
	DD	02H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$4
	DD	00H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$4
	DD	06H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$5
	DD	07H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$6
	DD	08H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$7
	DD	09H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$8
	DD	0aH
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$9
	DD	09H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$9
	DD	08H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$9
	DD	07H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$9
	DD	0eH
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$10
	DD	0fH
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$11
	DD	07H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$12
	DD	011H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$13
	DD	012H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$14
	DD	013H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$15
	DD	012H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$15
	DD	011H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$15
	DD	07H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$15
	DD	017H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$16
	DD	018H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$17
	DD	017H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$18
	DD	017H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$19
	DD	017H
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$20
	DD	01cH
	DD	FLAT:__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$21
; Function compile flags: /Odtp
xdata$x	ENDS
_TEXT	SEGMENT
tv339 = -668						; size = 4
tv202 = -664						; size = 4
tv337 = -660						; size = 4
tv207 = -656						; size = 4
tv335 = -652						; size = 4
tv182 = -648						; size = 4
tv329 = -644						; size = 4
tv160 = -640						; size = 4
tv327 = -636						; size = 4
tv158 = -632						; size = 4
tv324 = -628						; size = 4
tv171 = -624						; size = 4
tv315 = -620						; size = 4
tv64 = -616						; size = 4
$T143555 = -609						; size = 1
$T143554 = -608						; size = 28
$T143553 = -577						; size = 1
$T143552 = -576						; size = 4
$T143551 = -572						; size = 28
$T143550 = -544						; size = 28
$T143549 = -516						; size = 28
$T143548 = -488						; size = 28
$T143547 = -460						; size = 28
$T143546 = -432						; size = 28
$T143545 = -404						; size = 28
$T143544 = -376						; size = 28
$T143543 = -348						; size = 28
$T143542 = -320						; size = 28
$T143541 = -292						; size = 28
$T143540 = -264						; size = 28
$T143539 = -233						; size = 1
$T143538 = -232						; size = 4
_wscXML$139203 = -228					; size = 28
_i$139199 = -200					; size = 4
_iTargetClientID$139186 = -196				; size = 4
_iShip$139184 = -192					; size = 4
_iTargetShip$139185 = -188				; size = 4
_wszTargetName$ = -184					; size = 4
_wscXML$ = -180						; size = 28
_message$ = -152					; size = 24
_wscCommand$ = -128					; size = 4
_caption$ = -124					; size = 24
_scFilePath$ = -100					; size = 28
_wscPlayerInfo$ = -72					; size = 28
_$S1$ = -44						; size = 28
__$ArrayPad$ = -16					; size = 4
__$EHRec$ = -12						; size = 12
_iClientID$ = 8						; size = 4
_wscCmd$ = 12						; size = 4
_wscParam$ = 16						; size = 4
_usage$ = 20						; size = 4
?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z PROC ; PlayerInfo::UserCmd_ShowInfo
; File g:\max\bastelstube\fl\flhook source\flhookplugin_mod\plugins\playercntl_plugin\src\playerinfo.cpp
; Line 67
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 656				; 00000290H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
; Line 68
	mov	DWORD PTR _wszTargetName$[ebp], 0
; Line 69
	push	0
	push	32					; 00000020H
	mov	eax, DWORD PTR _wscParam$[ebp]
	push	eax
	lea	ecx, DWORD PTR _$S1$[ebp]
	push	ecx
	call	DWORD PTR __imp_?GetParam@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV12@GI@Z
	add	esp, 16					; 00000010H
	mov	DWORD PTR __$EHRec$[ebp+8], 0
	lea	edx, DWORD PTR _$S1$[ebp]
	mov	DWORD PTR _wscCommand$[ebp], edx
; Line 70
	push	OFFSET $SG139182
	mov	eax, DWORD PTR _wscCommand$[ebp]
	push	eax
	call	DWORD PTR __imp_??$?8GU?$char_traits@G@std@@V?$allocator@G@1@@std@@YA_NABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@0@PBG@Z
	add	esp, 8
	movzx	ecx, al
	test	ecx, ecx
	je	SHORT $LN10@UserCmd_Sh
; Line 72
	mov	edx, DWORD PTR _iClientID$[ebp]
	push	edx
	mov	ecx, DWORD PTR __imp_?Players@@3VPlayerDB@@A
	call	DWORD PTR __imp_?GetActiveCharacterName@PlayerDB@@QBEPBGI@Z
	mov	DWORD PTR _wszTargetName$[ebp], eax
; Line 74
	jmp	SHORT $LN9@UserCmd_Sh
$LN10@UserCmd_Sh:
; Line 77
	lea	eax, DWORD PTR _iShip$139184[ebp]
	push	eax
	lea	ecx, DWORD PTR _iClientID$[ebp]
	push	ecx
	call	DWORD PTR __imp_?GetShip@Player@pub@@YAHABIAAI@Z
	add	esp, 8
; Line 80
	lea	edx, DWORD PTR _iTargetShip$139185[ebp]
	push	edx
	lea	eax, DWORD PTR _iShip$139184[ebp]
	push	eax
	call	DWORD PTR __imp_?GetTarget@SpaceObj@pub@@YAHABIAAI@Z
	add	esp, 8
; Line 82
	mov	ecx, DWORD PTR _iTargetShip$139185[ebp]
	push	ecx
	call	DWORD PTR __imp_?HkGetClientIDByShip@@YAII@Z
	add	esp, 4
	mov	DWORD PTR _iTargetClientID$139186[ebp], eax
; Line 83
	mov	edx, DWORD PTR _iTargetClientID$139186[ebp]
	push	edx
	call	DWORD PTR __imp_?HkIsValidClientID@@YA_NI@Z
	add	esp, 4
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN9@UserCmd_Sh
; Line 84
	mov	ecx, DWORD PTR _iTargetClientID$139186[ebp]
	push	ecx
	mov	ecx, DWORD PTR __imp_?Players@@3VPlayerDB@@A
	call	DWORD PTR __imp_?GetActiveCharacterName@PlayerDB@@QBEPBGI@Z
	mov	DWORD PTR _wszTargetName$[ebp], eax
$LN9@UserCmd_Sh:
; Line 87
	cmp	DWORD PTR _wszTargetName$[ebp], 0
	jne	SHORT $LN7@UserCmd_Sh
; Line 89
	sub	esp, 28					; 0000001cH
	mov	ecx, esp
	mov	DWORD PTR $T143538[ebp], esp
	push	OFFSET $SG139190
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	DWORD PTR tv64[ebp], eax
	mov	edx, DWORD PTR tv64[ebp]
	mov	DWORD PTR tv315[ebp], edx
	mov	BYTE PTR __$EHRec$[ebp+8], 1
	mov	eax, DWORD PTR _iClientID$[ebp]
	push	eax
	mov	BYTE PTR __$EHRec$[ebp+8], 0
	call	DWORD PTR __imp_?PrintUserCmdText@@YAXIV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ZZ
	add	esp, 32					; 00000020H
; Line 90
	mov	BYTE PTR $T143539[ebp], 1
	mov	DWORD PTR __$EHRec$[ebp+8], -1
	lea	ecx, DWORD PTR _$S1$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	al, BYTE PTR $T143539[ebp]
	jmp	$LN11@UserCmd_Sh
$LN7@UserCmd_Sh:
; Line 93
	push	OFFSET $SG139196
	lea	ecx, DWORD PTR $T143540[ebp]
	call	DWORD PTR __imp_??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@PBD@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 2
	mov	ecx, DWORD PTR _wszTargetName$[ebp]
	push	ecx
	lea	ecx, DWORD PTR $T143541[ebp]
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 3
	lea	edx, DWORD PTR $T143540[ebp]
	push	edx
	lea	eax, DWORD PTR $T143541[ebp]
	push	eax
	lea	ecx, DWORD PTR _scFilePath$[ebp]
	push	ecx
	call	?GetUserFilePath@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@2@ABV12@@Z ; GetUserFilePath
	add	esp, 12					; 0000000cH
	mov	BYTE PTR __$EHRec$[ebp+8], 5
	lea	ecx, DWORD PTR $T143541[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 6
	lea	ecx, DWORD PTR $T143540[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
; Line 94
	push	OFFSET $SG139198
	lea	ecx, DWORD PTR _wscPlayerInfo$[ebp]
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 7
; Line 95
	mov	DWORD PTR _i$139199[ebp], 1
	jmp	SHORT $LN6@UserCmd_Sh
$LN5@UserCmd_Sh:
	mov	edx, DWORD PTR _i$139199[ebp]
	add	edx, 1
	mov	DWORD PTR _i$139199[ebp], edx
$LN6@UserCmd_Sh:
	cmp	DWORD PTR _i$139199[ebp], 5
	jg	$LN4@UserCmd_Sh
; Line 97
	push	OFFSET $SG139208
	lea	ecx, DWORD PTR $T143542[ebp]
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 8
	push	OFFSET $SG139209
	lea	ecx, DWORD PTR $T143544[ebp]
	call	DWORD PTR __imp_??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@PBD@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 9
	lea	eax, DWORD PTR $T143542[ebp]
	push	eax
	mov	ecx, DWORD PTR _i$139199[ebp]
	push	ecx
	lea	edx, DWORD PTR $T143543[ebp]
	push	edx
	call	DWORD PTR __imp_?itos@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z
	add	esp, 8
	mov	DWORD PTR tv171[ebp], eax
	mov	eax, DWORD PTR tv171[ebp]
	mov	DWORD PTR tv324[ebp], eax
	mov	BYTE PTR __$EHRec$[ebp+8], 10		; 0000000aH
	mov	ecx, DWORD PTR tv324[ebp]
	push	ecx
	lea	edx, DWORD PTR $T143544[ebp]
	push	edx
	lea	eax, DWORD PTR _scFilePath$[ebp]
	push	eax
	lea	ecx, DWORD PTR _wscXML$139203[ebp]
	push	ecx
	call	?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z ; PlayerInfo::IniGetLongWS
	add	esp, 20					; 00000014H
	mov	BYTE PTR __$EHRec$[ebp+8], 12		; 0000000cH
	lea	ecx, DWORD PTR $T143543[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 13		; 0000000dH
	lea	ecx, DWORD PTR $T143544[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 14		; 0000000eH
	lea	ecx, DWORD PTR $T143542[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
; Line 98
	lea	ecx, DWORD PTR _wscXML$139203[ebp]
	call	DWORD PTR __imp_?length@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QBEIXZ
	test	eax, eax
	je	$LN3@UserCmd_Sh
; Line 99
	push	OFFSET $SG139213
	lea	edx, DWORD PTR _wscXML$139203[ebp]
	push	edx
	push	OFFSET $SG139214
	lea	eax, DWORD PTR $T143545[ebp]
	push	eax
	call	DWORD PTR __imp_??$?HGU?$char_traits@G@std@@V?$allocator@G@1@@std@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@0@PBGABV10@@Z
	add	esp, 12					; 0000000cH
	mov	DWORD PTR tv158[ebp], eax
	mov	ecx, DWORD PTR tv158[ebp]
	mov	DWORD PTR tv327[ebp], ecx
	mov	BYTE PTR __$EHRec$[ebp+8], 15		; 0000000fH
	mov	edx, DWORD PTR tv327[ebp]
	push	edx
	lea	eax, DWORD PTR $T143546[ebp]
	push	eax
	call	DWORD PTR __imp_??$?HGU?$char_traits@G@std@@V?$allocator@G@1@@std@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@0@ABV10@PBG@Z
	add	esp, 12					; 0000000cH
	mov	DWORD PTR tv160[ebp], eax
	mov	ecx, DWORD PTR tv160[ebp]
	mov	DWORD PTR tv329[ebp], ecx
	mov	BYTE PTR __$EHRec$[ebp+8], 16		; 00000010H
	mov	edx, DWORD PTR tv329[ebp]
	push	edx
	lea	ecx, DWORD PTR _wscPlayerInfo$[ebp]
	call	DWORD PTR __imp_??Y?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAEAAV01@ABV01@@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 15		; 0000000fH
	lea	ecx, DWORD PTR $T143546[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 14		; 0000000eH
	lea	ecx, DWORD PTR $T143545[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
$LN3@UserCmd_Sh:
; Line 100
	mov	BYTE PTR __$EHRec$[ebp+8], 7
	lea	ecx, DWORD PTR _wscXML$139203[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	jmp	$LN5@UserCmd_Sh
$LN4@UserCmd_Sh:
; Line 101
	push	OFFSET $SG139220
	lea	ecx, DWORD PTR $T143547[ebp]
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 17		; 00000011H
	push	OFFSET $SG139221
	lea	ecx, DWORD PTR $T143548[ebp]
	call	DWORD PTR __imp_??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@PBD@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 18		; 00000012H
	push	OFFSET $SG139222
	lea	ecx, DWORD PTR $T143549[ebp]
	call	DWORD PTR __imp_??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@PBD@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 19		; 00000013H
	lea	eax, DWORD PTR $T143547[ebp]
	push	eax
	lea	ecx, DWORD PTR $T143548[ebp]
	push	ecx
	lea	edx, DWORD PTR $T143549[ebp]
	push	edx
	lea	eax, DWORD PTR _scFilePath$[ebp]
	push	eax
	lea	ecx, DWORD PTR _wscXML$[ebp]
	push	ecx
	call	?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z ; PlayerInfo::IniGetLongWS
	add	esp, 20					; 00000014H
	mov	BYTE PTR __$EHRec$[ebp+8], 21		; 00000015H
	lea	ecx, DWORD PTR $T143549[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 22		; 00000016H
	lea	ecx, DWORD PTR $T143548[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 23		; 00000017H
	lea	ecx, DWORD PTR $T143547[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
; Line 102
	lea	ecx, DWORD PTR _wscXML$[ebp]
	call	DWORD PTR __imp_?length@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QBEIXZ
	test	eax, eax
	je	$LN2@UserCmd_Sh
; Line 103
	push	OFFSET $SG139226
	lea	edx, DWORD PTR _wscXML$[ebp]
	push	edx
	push	OFFSET $SG139227
	lea	eax, DWORD PTR $T143550[ebp]
	push	eax
	call	DWORD PTR __imp_??$?HGU?$char_traits@G@std@@V?$allocator@G@1@@std@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@0@PBGABV10@@Z
	add	esp, 12					; 0000000cH
	mov	DWORD PTR tv182[ebp], eax
	mov	ecx, DWORD PTR tv182[ebp]
	mov	DWORD PTR tv335[ebp], ecx
	mov	BYTE PTR __$EHRec$[ebp+8], 24		; 00000018H
	mov	edx, DWORD PTR tv335[ebp]
	push	edx
	lea	eax, DWORD PTR $T143551[ebp]
	push	eax
	call	DWORD PTR __imp_??$?HGU?$char_traits@G@std@@V?$allocator@G@1@@std@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@0@ABV10@PBG@Z
	add	esp, 12					; 0000000cH
	mov	DWORD PTR tv207[ebp], eax
	mov	ecx, DWORD PTR tv207[ebp]
	mov	DWORD PTR tv337[ebp], ecx
	mov	BYTE PTR __$EHRec$[ebp+8], 25		; 00000019H
	mov	edx, DWORD PTR tv337[ebp]
	push	edx
	lea	ecx, DWORD PTR _wscPlayerInfo$[ebp]
	call	DWORD PTR __imp_??Y?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAEAAV01@ABV01@@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 24		; 00000018H
	lea	ecx, DWORD PTR $T143551[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 23		; 00000017H
	lea	ecx, DWORD PTR $T143550[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
$LN2@UserCmd_Sh:
; Line 104
	push	OFFSET $SG139228
	lea	ecx, DWORD PTR _wscPlayerInfo$[ebp]
	call	DWORD PTR __imp_??Y?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAEAAV01@PBG@Z
; Line 106
	lea	ecx, DWORD PTR _wscPlayerInfo$[ebp]
	call	DWORD PTR __imp_?length@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QBEIXZ
	cmp	eax, 30					; 0000001eH
	jae	$LN1@UserCmd_Sh
; Line 108
	sub	esp, 28					; 0000001cH
	mov	ecx, esp
	mov	DWORD PTR $T143552[ebp], esp
	push	OFFSET $SG139231
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	DWORD PTR tv202[ebp], eax
	mov	eax, DWORD PTR tv202[ebp]
	mov	DWORD PTR tv339[ebp], eax
	mov	BYTE PTR __$EHRec$[ebp+8], 26		; 0000001aH
	mov	ecx, DWORD PTR _iClientID$[ebp]
	push	ecx
	mov	BYTE PTR __$EHRec$[ebp+8], 23		; 00000017H
	call	DWORD PTR __imp_?PrintUserCmdText@@YAXIV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ZZ
	add	esp, 32					; 00000020H
; Line 109
	mov	BYTE PTR $T143553[ebp], 1
	mov	BYTE PTR __$EHRec$[ebp+8], 7
	lea	ecx, DWORD PTR _wscXML$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 6
	lea	ecx, DWORD PTR _wscPlayerInfo$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 0
	lea	ecx, DWORD PTR _scFilePath$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
	mov	DWORD PTR __$EHRec$[ebp+8], -1
	lea	ecx, DWORD PTR _$S1$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	al, BYTE PTR $T143553[ebp]
	jmp	$LN11@UserCmd_Sh
$LN1@UserCmd_Sh:
; Line 112
	mov	edx, DWORD PTR _wszTargetName$[ebp]
	push	edx
	lea	ecx, DWORD PTR $T143554[ebp]
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 27		; 0000001bH
	lea	eax, DWORD PTR $T143554[ebp]
	push	eax
	push	500000					; 0007a120H
	mov	ecx, DWORD PTR _iClientID$[ebp]
	push	ecx
	call	?HkChangeIDSString@@YAXIIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z ; HkChangeIDSString
	add	esp, 12					; 0000000cH
	mov	BYTE PTR __$EHRec$[ebp+8], 23		; 00000017H
	lea	ecx, DWORD PTR $T143554[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
; Line 113
	lea	edx, DWORD PTR _wscPlayerInfo$[ebp]
	push	edx
	push	500001					; 0007a121H
	mov	eax, DWORD PTR _iClientID$[ebp]
	push	eax
	call	?HkChangeIDSString@@YAXIIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z ; HkChangeIDSString
	add	esp, 12					; 0000000cH
; Line 115
	push	0
	push	0
	lea	ecx, DWORD PTR _caption$[ebp]
	call	DWORD PTR __imp_??0FmtStr@@QAE@IPBUVal@0@@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 28		; 0000001cH
; Line 116
	push	500000					; 0007a120H
	lea	ecx, DWORD PTR _caption$[ebp]
	call	DWORD PTR __imp_?begin_mad_lib@FmtStr@@QAEXI@Z
; Line 117
	lea	ecx, DWORD PTR _caption$[ebp]
	call	DWORD PTR __imp_?end_mad_lib@FmtStr@@QAEXXZ
; Line 119
	push	0
	push	0
	lea	ecx, DWORD PTR _message$[ebp]
	call	DWORD PTR __imp_??0FmtStr@@QAE@IPBUVal@0@@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 29		; 0000001dH
; Line 120
	push	500001					; 0007a121H
	lea	ecx, DWORD PTR _message$[ebp]
	call	DWORD PTR __imp_?begin_mad_lib@FmtStr@@QAEXI@Z
; Line 121
	lea	ecx, DWORD PTR _message$[ebp]
	call	DWORD PTR __imp_?end_mad_lib@FmtStr@@QAEXXZ
; Line 123
	push	8
	lea	ecx, DWORD PTR _message$[ebp]
	push	ecx
	lea	edx, DWORD PTR _caption$[ebp]
	push	edx
	mov	eax, DWORD PTR _iClientID$[ebp]
	push	eax
	call	DWORD PTR __imp_?PopUpDialog@Player@pub@@YAHIABUFmtStr@@0I@Z
	add	esp, 16					; 00000010H
; Line 124
	mov	BYTE PTR $T143555[ebp], 1
	mov	BYTE PTR __$EHRec$[ebp+8], 28		; 0000001cH
	lea	ecx, DWORD PTR _message$[ebp]
	call	DWORD PTR __imp_??1FmtStr@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 23		; 00000017H
	lea	ecx, DWORD PTR _caption$[ebp]
	call	DWORD PTR __imp_??1FmtStr@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 7
	lea	ecx, DWORD PTR _wscXML$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 6
	lea	ecx, DWORD PTR _wscPlayerInfo$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 0
	lea	ecx, DWORD PTR _scFilePath$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
	mov	DWORD PTR __$EHRec$[ebp+8], -1
	lea	ecx, DWORD PTR _$S1$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	al, BYTE PTR $T143555[ebp]
$LN11@UserCmd_Sh:
; Line 125
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	mov	esp, ebp
	pop	ebp
	ret	0
_TEXT	ENDS
text$x	SEGMENT
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$0:
	lea	ecx, DWORD PTR _$S1$[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$1:
	mov	ecx, DWORD PTR $T143538[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$2:
	lea	ecx, DWORD PTR $T143540[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$3:
	lea	ecx, DWORD PTR $T143541[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$4:
	lea	ecx, DWORD PTR _scFilePath$[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$5:
	lea	ecx, DWORD PTR _wscPlayerInfo$[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$6:
	lea	ecx, DWORD PTR $T143542[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$7:
	lea	ecx, DWORD PTR $T143544[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$8:
	lea	ecx, DWORD PTR $T143543[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$9:
	lea	ecx, DWORD PTR _wscXML$139203[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$10:
	lea	ecx, DWORD PTR $T143545[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$11:
	lea	ecx, DWORD PTR $T143546[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$12:
	lea	ecx, DWORD PTR $T143547[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$13:
	lea	ecx, DWORD PTR $T143548[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$14:
	lea	ecx, DWORD PTR $T143549[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$15:
	lea	ecx, DWORD PTR _wscXML$[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$16:
	lea	ecx, DWORD PTR $T143550[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$17:
	lea	ecx, DWORD PTR $T143551[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$18:
	mov	ecx, DWORD PTR $T143552[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$19:
	lea	ecx, DWORD PTR $T143554[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$20:
	lea	ecx, DWORD PTR _caption$[ebp]
	jmp	DWORD PTR __imp_??1FmtStr@@QAE@XZ
__unwindfunclet$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$21:
	lea	ecx, DWORD PTR _message$[ebp]
	jmp	DWORD PTR __imp_??1FmtStr@@QAE@XZ
__ehhandler$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-660]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	ecx, DWORD PTR [edx-4]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
?UserCmd_ShowInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z ENDP ; PlayerInfo::UserCmd_ShowInfo
PUBLIC	__$ArrayPad$
EXTRN	__imp_?append@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAEAAV12@IG@Z:PROC
EXTRN	__imp_??4?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAEAAV01@ABV01@@Z:PROC
EXTRN	__imp_?substr@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBE?AV12@II@Z:PROC
EXTRN	__imp_?npos@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@2IB:DWORD
EXTRN	__imp__sscanf:PROC
EXTRN	__imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@ABV01@@Z:PROC
EXTRN	__imp_?length@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBEIXZ:PROC
EXTRN	__imp__GetPrivateProfileStringA@24:PROC
EXTRN	__imp_?c_str@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBEPBDXZ:PROC
EXTRN	__chkstk:PROC
xdata$x	SEGMENT
__unwindtable$?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z$1
	DD	00H
	DD	FLAT:__unwindfunclet$?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z$0
	DD	01H
	DD	FLAT:__unwindfunclet$?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z$2
	DD	02H
	DD	FLAT:__unwindfunclet$?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z$3
__ehfuncinfo$?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z DD 019930522H
	DD	04H
	DD	FLAT:__unwindtable$?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	00H
; Function compile flags: /Odtp
xdata$x	ENDS
_TEXT	SEGMENT
tv158 = -65664						; size = 4
tv88 = -65660						; size = 4
$T143592 = -65656					; size = 4
$T143589 = -65652					; size = 28
_wChar$139079 = -65624					; size = 2
_lHiByte$ = -65620					; size = 4
_lLoByte$ = -65616					; size = 4
_wscValue$ = -65612					; size = 28
_scValue$ = -65584					; size = 28
_szRet$ = -65556					; size = 65536
__$ArrayPad$ = -16					; size = 4
__$EHRec$ = -12						; size = 12
___$ReturnUdt$ = 8					; size = 4
_scFile$ = 12						; size = 4
_scApp$ = 16						; size = 4
_scKey$ = 20						; size = 4
_wscDefault$ = 24					; size = 4
?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z PROC ; PlayerInfo::IniGetLongWS
; Line 46
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	mov	eax, 65652				; 00010074H
	call	__chkstk
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR $T143592[ebp], 0
; Line 48
	mov	ecx, DWORD PTR _scFile$[ebp]
	call	DWORD PTR __imp_?c_str@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBEPBDXZ
	push	eax
	push	65536					; 00010000H
	lea	eax, DWORD PTR _szRet$[ebp]
	push	eax
	push	OFFSET $SG139067
	mov	ecx, DWORD PTR _scKey$[ebp]
	call	DWORD PTR __imp_?c_str@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBEPBDXZ
	push	eax
	mov	ecx, DWORD PTR _scApp$[ebp]
	call	DWORD PTR __imp_?c_str@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBEPBDXZ
	push	eax
	call	DWORD PTR __imp__GetPrivateProfileStringA@24
; Line 49
	lea	ecx, DWORD PTR _szRet$[ebp]
	push	ecx
	lea	ecx, DWORD PTR _scValue$[ebp]
	call	DWORD PTR __imp_??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@PBD@Z
	mov	DWORD PTR __$EHRec$[ebp+8], 1
; Line 50
	lea	ecx, DWORD PTR _scValue$[ebp]
	call	DWORD PTR __imp_?length@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBEIXZ
	test	eax, eax
	jne	SHORT $LN3@IniGetLong
; Line 51
	mov	edx, DWORD PTR _wscDefault$[ebp]
	push	edx
	mov	ecx, DWORD PTR ___$ReturnUdt$[ebp]
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@ABV01@@Z
	mov	eax, DWORD PTR $T143592[ebp]
	or	eax, 1
	mov	DWORD PTR $T143592[ebp], eax
	mov	BYTE PTR __$EHRec$[ebp+8], 0
	lea	ecx, DWORD PTR _scValue$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
	mov	eax, DWORD PTR ___$ReturnUdt$[ebp]
	jmp	$LN4@IniGetLong
$LN3@IniGetLong:
; Line 53
	push	OFFSET $SG139071
	lea	ecx, DWORD PTR _wscValue$[ebp]
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 2
$LN2@IniGetLong:
; Line 56
	lea	ecx, DWORD PTR _lLoByte$[ebp]
	push	ecx
	lea	edx, DWORD PTR _lHiByte$[ebp]
	push	edx
	push	OFFSET $SG139077
	lea	ecx, DWORD PTR _scValue$[ebp]
	call	DWORD PTR __imp_?c_str@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBEPBDXZ
	push	eax
	call	DWORD PTR __imp__sscanf
	add	esp, 16					; 00000010H
	cmp	eax, 2
	jne	$LN1@IniGetLong
; Line 58
	mov	eax, DWORD PTR __imp_?npos@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@2IB
	mov	ecx, DWORD PTR [eax]
	push	ecx
	push	4
	lea	edx, DWORD PTR $T143589[ebp]
	push	edx
	lea	ecx, DWORD PTR _scValue$[ebp]
	call	DWORD PTR __imp_?substr@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBE?AV12@II@Z
	mov	DWORD PTR tv88[ebp], eax
	mov	eax, DWORD PTR tv88[ebp]
	mov	DWORD PTR tv158[ebp], eax
	mov	BYTE PTR __$EHRec$[ebp+8], 3
	mov	ecx, DWORD PTR tv158[ebp]
	push	ecx
	lea	ecx, DWORD PTR _scValue$[ebp]
	call	DWORD PTR __imp_??4?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAEAAV01@ABV01@@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 2
	lea	ecx, DWORD PTR $T143589[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
; Line 59
	mov	edx, DWORD PTR _lHiByte$[ebp]
	shl	edx, 8
	or	edx, DWORD PTR _lLoByte$[ebp]
	mov	WORD PTR _wChar$139079[ebp], dx
; Line 60
	movzx	eax, WORD PTR _wChar$139079[ebp]
	push	eax
	push	1
	lea	ecx, DWORD PTR _wscValue$[ebp]
	call	DWORD PTR __imp_?append@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAEAAV12@IG@Z
; Line 61
	jmp	$LN2@IniGetLong
$LN1@IniGetLong:
; Line 63
	lea	ecx, DWORD PTR _wscValue$[ebp]
	push	ecx
	mov	ecx, DWORD PTR ___$ReturnUdt$[ebp]
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@ABV01@@Z
	mov	edx, DWORD PTR $T143592[ebp]
	or	edx, 1
	mov	DWORD PTR $T143592[ebp], edx
	mov	BYTE PTR __$EHRec$[ebp+8], 1
	lea	ecx, DWORD PTR _wscValue$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 0
	lea	ecx, DWORD PTR _scValue$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
	mov	eax, DWORD PTR ___$ReturnUdt$[ebp]
$LN4@IniGetLong:
; Line 64
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	mov	esp, ebp
	pop	ebp
	ret	0
_TEXT	ENDS
text$x	SEGMENT
__unwindfunclet$?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z$0:
	lea	ecx, DWORD PTR _scValue$[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
__unwindfunclet$?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z$1:
	mov	eax, DWORD PTR $T143592[ebp]
	and	eax, 1
	je	$LN8@IniGetLong
	and	DWORD PTR $T143592[ebp], -2		; fffffffeH
	mov	ecx, DWORD PTR ___$ReturnUdt$[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
$LN8@IniGetLong:
	ret	0
__unwindfunclet$?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z$2:
	lea	ecx, DWORD PTR _wscValue$[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z$3:
	lea	ecx, DWORD PTR $T143589[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
__ehhandler$?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-65656]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	ecx, DWORD PTR [edx-4]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z ENDP ; PlayerInfo::IniGetLongWS
PUBLIC	__$ArrayPad$
PUBLIC	?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z ; PlayerInfo::UserCmd_SetInfo
EXTRN	__imp_?IniWriteW@@YAXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00ABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@2@@Z:PROC
EXTRN	__imp_??$?HGU?$char_traits@G@std@@V?$allocator@G@1@@std@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@0@ABV10@0@Z:PROC
EXTRN	__imp_?XMLText@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV12@@Z:PROC
EXTRN	?GetParamToEnd@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV12@GI@Z:PROC ; GetParamToEnd
EXTRN	__imp_?ToInt@@YAHABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z:PROC
xdata$x	SEGMENT
__ehfuncinfo$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z DD 019930522H
	DD	01fH
	DD	FLAT:__unwindtable$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	00H
__unwindtable$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$0
	DD	0ffffffffH
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$1
	DD	01H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$2
	DD	02H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$3
	DD	03H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$4
	DD	04H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$5
	DD	03H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$5
	DD	02H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$5
	DD	07H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$6
	DD	07H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$7
	DD	09H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$8
	DD	0aH
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$9
	DD	0bH
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$10
	DD	0cH
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$11
	DD	0dH
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$12
	DD	0cH
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$12
	DD	0bH
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$12
	DD	0aH
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$12
	DD	09H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$12
	DD	07H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$12
	DD	013H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$13
	DD	014H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$14
	DD	013H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$15
	DD	07H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$16
	DD	017H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$17
	DD	018H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$18
	DD	07H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$19
	DD	07H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$20
	DD	07H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$21
	DD	07H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$22
	DD	07H
	DD	FLAT:__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$23
; Function compile flags: /Odtp
xdata$x	ENDS
_TEXT	SEGMENT
tv404 = -652						; size = 4
tv415 = -648						; size = 4
tv402 = -644						; size = 4
tv413 = -640						; size = 4
tv399 = -636						; size = 4
tv411 = -632						; size = 4
tv397 = -628						; size = 4
tv409 = -624						; size = 4
tv395 = -620						; size = 4
tv234 = -616						; size = 4
tv393 = -612						; size = 4
tv245 = -608						; size = 4
tv389 = -604						; size = 4
tv165 = -600						; size = 4
tv385 = -596						; size = 4
tv204 = -592						; size = 4
tv381 = -588						; size = 4
tv87 = -584						; size = 4
tv379 = -580						; size = 4
tv174 = -576						; size = 4
tv377 = -572						; size = 4
tv185 = -568						; size = 4
tv370 = -564						; size = 4
tv85 = -560						; size = 4
tv359 = -556						; size = 4
tv408 = -552						; size = 4
$T143625 = -545						; size = 1
$T143624 = -544						; size = 4
$T143623 = -540						; size = 4
$T143622 = -536						; size = 4
$T143621 = -532						; size = 4
$T143620 = -528						; size = 4
$T143619 = -524						; size = 28
$T143618 = -496						; size = 28
$T143617 = -468						; size = 28
$T143616 = -440						; size = 4
$T143615 = -436						; size = 28
$T143614 = -408						; size = 28
$T143613 = -380						; size = 28
$T143612 = -352						; size = 28
$T143611 = -324						; size = 28
$T143610 = -296						; size = 28
$T143609 = -268						; size = 28
$T143608 = -237						; size = 1
$T143607 = -236						; size = 4
$T143606 = -229						; size = 1
$T143605 = -228						; size = 28
$T143604 = -200						; size = 28
$T143603 = -172						; size = 28
_wscNewMsg$139279 = -144				; size = 28
_length$139274 = -116					; size = 4
_iPara$ = -112						; size = 4
_wscMsg$ = -108						; size = 4
_wscCommand$ = -104					; size = 4
_$S3$ = -100						; size = 28
_scFilePath$ = -72					; size = 28
_$S2$ = -44						; size = 28
__$ArrayPad$ = -16					; size = 4
__$EHRec$ = -12						; size = 12
_iClientID$ = 8						; size = 4
_wscCmd$ = 12						; size = 4
_wscParam$ = 16						; size = 4
_usage$ = 20						; size = 4
?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z PROC ; PlayerInfo::UserCmd_SetInfo
; Line 138
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 640				; 00000280H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	push	esi
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
; Line 139
	push	0
	push	32					; 00000020H
	mov	eax, DWORD PTR _wscParam$[ebp]
	push	eax
	lea	ecx, DWORD PTR $T143603[ebp]
	push	ecx
	call	DWORD PTR __imp_?GetParam@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV12@GI@Z
	add	esp, 16					; 00000010H
	mov	DWORD PTR tv408[ebp], eax
	mov	edx, DWORD PTR tv408[ebp]
	mov	DWORD PTR tv359[ebp], edx
	mov	DWORD PTR __$EHRec$[ebp+8], 0
	mov	eax, DWORD PTR tv359[ebp]
	push	eax
	call	DWORD PTR __imp_?ToInt@@YAHABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z
	add	esp, 4
	mov	DWORD PTR _iPara$[ebp], eax
	mov	DWORD PTR __$EHRec$[ebp+8], -1
	lea	ecx, DWORD PTR $T143603[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
; Line 140
	push	1
	push	32					; 00000020H
	mov	ecx, DWORD PTR _wscParam$[ebp]
	push	ecx
	lea	edx, DWORD PTR _$S2$[ebp]
	push	edx
	call	DWORD PTR __imp_?GetParam@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV12@GI@Z
	add	esp, 16					; 00000010H
	mov	DWORD PTR __$EHRec$[ebp+8], 1
	lea	eax, DWORD PTR _$S2$[ebp]
	mov	DWORD PTR _wscCommand$[ebp], eax
; Line 141
	push	2
	push	32					; 00000020H
	mov	ecx, DWORD PTR _wscParam$[ebp]
	push	ecx
	lea	edx, DWORD PTR _$S3$[ebp]
	push	edx
	call	?GetParamToEnd@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV12@GI@Z ; GetParamToEnd
	add	esp, 16					; 00000010H
	mov	BYTE PTR __$EHRec$[ebp+8], 2
	lea	eax, DWORD PTR _$S3$[ebp]
	mov	DWORD PTR _wscMsg$[ebp], eax
; Line 143
	push	OFFSET $SG139269
	lea	ecx, DWORD PTR $T143604[ebp]
	call	DWORD PTR __imp_??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@PBD@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 3
	mov	ecx, DWORD PTR _iClientID$[ebp]
	push	ecx
	mov	ecx, DWORD PTR __imp_?Players@@3VPlayerDB@@A
	call	DWORD PTR __imp_?GetActiveCharacterName@PlayerDB@@QBEPBGI@Z
	push	eax
	lea	ecx, DWORD PTR $T143605[ebp]
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 4
	lea	edx, DWORD PTR $T143604[ebp]
	push	edx
	lea	eax, DWORD PTR $T143605[ebp]
	push	eax
	lea	ecx, DWORD PTR _scFilePath$[ebp]
	push	ecx
	call	?GetUserFilePath@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@2@ABV12@@Z ; GetUserFilePath
	add	esp, 12					; 0000000cH
	mov	BYTE PTR __$EHRec$[ebp+8], 6
	lea	ecx, DWORD PTR $T143605[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 7
	lea	ecx, DWORD PTR $T143604[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
; Line 144
	lea	ecx, DWORD PTR _scFilePath$[ebp]
	call	DWORD PTR __imp_?length@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBEIXZ
	test	eax, eax
	jne	SHORT $LN6@UserCmd_Se
; Line 145
	mov	BYTE PTR $T143606[ebp], 0
	mov	BYTE PTR __$EHRec$[ebp+8], 2
	lea	ecx, DWORD PTR _scFilePath$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 1
	lea	ecx, DWORD PTR _$S3$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	DWORD PTR __$EHRec$[ebp+8], -1
	lea	ecx, DWORD PTR _$S2$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	al, BYTE PTR $T143606[ebp]
	jmp	$LN7@UserCmd_Se
$LN6@UserCmd_Se:
; Line 147
	cmp	DWORD PTR _iPara$[ebp], 0
	jbe	$LN5@UserCmd_Se
	cmp	DWORD PTR _iPara$[ebp], 5
	ja	$LN5@UserCmd_Se
	push	OFFSET $SG139273
	mov	edx, DWORD PTR _wscCommand$[ebp]
	push	edx
	call	DWORD PTR __imp_??$?8GU?$char_traits@G@std@@V?$allocator@G@1@@std@@YA_NABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@0@PBG@Z
	add	esp, 8
	movzx	eax, al
	test	eax, eax
	je	$LN5@UserCmd_Se
; Line 149
	lea	ecx, DWORD PTR _scFilePath$[ebp]
	push	ecx
	call	?CurrLength@PlayerInfo@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z ; PlayerInfo::CurrLength
	add	esp, 4
	mov	esi, eax
	mov	ecx, DWORD PTR _wscMsg$[ebp]
	call	DWORD PTR __imp_?length@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QBEIXZ
	add	esi, eax
	mov	DWORD PTR _length$139274[ebp], esi
; Line 150
	cmp	DWORD PTR _length$139274[ebp], 1000	; 000003e8H
	jle	SHORT $LN4@UserCmd_Se
; Line 152
	push	1000					; 000003e8H
	sub	esp, 28					; 0000001cH
	mov	ecx, esp
	mov	DWORD PTR $T143607[ebp], esp
	push	OFFSET $SG139277
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	DWORD PTR tv85[ebp], eax
	mov	edx, DWORD PTR tv85[ebp]
	mov	DWORD PTR tv370[ebp], edx
	mov	BYTE PTR __$EHRec$[ebp+8], 8
	mov	eax, DWORD PTR _iClientID$[ebp]
	push	eax
	mov	BYTE PTR __$EHRec$[ebp+8], 7
	call	DWORD PTR __imp_?PrintUserCmdText@@YAXIV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ZZ
	add	esp, 36					; 00000024H
; Line 153
	mov	BYTE PTR $T143608[ebp], 0
	mov	BYTE PTR __$EHRec$[ebp+8], 2
	lea	ecx, DWORD PTR _scFilePath$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 1
	lea	ecx, DWORD PTR _$S3$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	DWORD PTR __$EHRec$[ebp+8], -1
	lea	ecx, DWORD PTR _$S2$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	al, BYTE PTR $T143608[ebp]
	jmp	$LN7@UserCmd_Se
$LN4@UserCmd_Se:
; Line 156
	push	OFFSET $SG139286
	lea	ecx, DWORD PTR $T143610[ebp]
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 9
	push	OFFSET $SG139287
	lea	ecx, DWORD PTR $T143612[ebp]
	call	DWORD PTR __imp_??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@PBD@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 10		; 0000000aH
	mov	ecx, DWORD PTR _wscMsg$[ebp]
	push	ecx
	lea	edx, DWORD PTR $T143609[ebp]
	push	edx
	call	DWORD PTR __imp_?XMLText@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV12@@Z
	add	esp, 8
	mov	DWORD PTR tv185[ebp], eax
	mov	eax, DWORD PTR tv185[ebp]
	mov	DWORD PTR tv377[ebp], eax
	mov	BYTE PTR __$EHRec$[ebp+8], 11		; 0000000bH
	mov	ecx, DWORD PTR tv377[ebp]
	push	ecx
	lea	edx, DWORD PTR $T143610[ebp]
	push	edx
	mov	eax, DWORD PTR _iPara$[ebp]
	push	eax
	lea	ecx, DWORD PTR $T143611[ebp]
	push	ecx
	call	DWORD PTR __imp_?itos@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z
	add	esp, 8
	mov	DWORD PTR tv174[ebp], eax
	mov	edx, DWORD PTR tv174[ebp]
	mov	DWORD PTR tv379[ebp], edx
	mov	BYTE PTR __$EHRec$[ebp+8], 12		; 0000000cH
	mov	eax, DWORD PTR tv379[ebp]
	push	eax
	lea	ecx, DWORD PTR $T143612[ebp]
	push	ecx
	lea	edx, DWORD PTR _scFilePath$[ebp]
	push	edx
	lea	eax, DWORD PTR $T143613[ebp]
	push	eax
	call	?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z ; PlayerInfo::IniGetLongWS
	add	esp, 20					; 00000014H
	mov	DWORD PTR tv87[ebp], eax
	mov	ecx, DWORD PTR tv87[ebp]
	mov	DWORD PTR tv381[ebp], ecx
	mov	BYTE PTR __$EHRec$[ebp+8], 13		; 0000000dH
	mov	edx, DWORD PTR tv381[ebp]
	push	edx
	lea	eax, DWORD PTR _wscNewMsg$139279[ebp]
	push	eax
	call	DWORD PTR __imp_??$?HGU?$char_traits@G@std@@V?$allocator@G@1@@std@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@0@ABV10@0@Z
	add	esp, 12					; 0000000cH
	mov	BYTE PTR __$EHRec$[ebp+8], 15		; 0000000fH
	lea	ecx, DWORD PTR $T143613[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 16		; 00000010H
	lea	ecx, DWORD PTR $T143611[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 17		; 00000011H
	lea	ecx, DWORD PTR $T143609[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 18		; 00000012H
	lea	ecx, DWORD PTR $T143612[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 19		; 00000013H
	lea	ecx, DWORD PTR $T143610[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
; Line 157
	push	OFFSET $SG139290
	lea	ecx, DWORD PTR $T143615[ebp]
	call	DWORD PTR __imp_??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@PBD@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 20		; 00000014H
	lea	ecx, DWORD PTR _wscNewMsg$139279[ebp]
	push	ecx
	mov	edx, DWORD PTR _iPara$[ebp]
	push	edx
	lea	eax, DWORD PTR $T143614[ebp]
	push	eax
	call	DWORD PTR __imp_?itos@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z
	add	esp, 8
	mov	DWORD PTR tv204[ebp], eax
	mov	ecx, DWORD PTR tv204[ebp]
	mov	DWORD PTR tv385[ebp], ecx
	mov	BYTE PTR __$EHRec$[ebp+8], 21		; 00000015H
	mov	edx, DWORD PTR tv385[ebp]
	push	edx
	lea	eax, DWORD PTR $T143615[ebp]
	push	eax
	lea	ecx, DWORD PTR _scFilePath$[ebp]
	push	ecx
	call	DWORD PTR __imp_?IniWriteW@@YAXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00ABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@2@@Z
	add	esp, 16					; 00000010H
	mov	BYTE PTR __$EHRec$[ebp+8], 20		; 00000014H
	lea	ecx, DWORD PTR $T143614[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 19		; 00000013H
	lea	ecx, DWORD PTR $T143615[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
; Line 158
	push	1000					; 000003e8H
	mov	edx, DWORD PTR _length$139274[ebp]
	push	edx
	sub	esp, 28					; 0000001cH
	mov	ecx, esp
	mov	DWORD PTR $T143616[ebp], esp
	push	OFFSET $SG139292
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	DWORD PTR tv165[ebp], eax
	mov	eax, DWORD PTR tv165[ebp]
	mov	DWORD PTR tv389[ebp], eax
	mov	BYTE PTR __$EHRec$[ebp+8], 22		; 00000016H
	mov	ecx, DWORD PTR _iClientID$[ebp]
	push	ecx
	mov	BYTE PTR __$EHRec$[ebp+8], 19		; 00000013H
	call	DWORD PTR __imp_?PrintUserCmdText@@YAXIV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ZZ
	add	esp, 40					; 00000028H
; Line 159
	mov	BYTE PTR __$EHRec$[ebp+8], 7
	lea	ecx, DWORD PTR _wscNewMsg$139279[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	jmp	$LN3@UserCmd_Se
$LN5@UserCmd_Se:
; Line 160
	cmp	DWORD PTR _iPara$[ebp], 0
	jbe	$LN2@UserCmd_Se
	cmp	DWORD PTR _iPara$[ebp], 5
	ja	$LN2@UserCmd_Se
	push	OFFSET $SG139295
	mov	edx, DWORD PTR _wscCommand$[ebp]
	push	edx
	call	DWORD PTR __imp_??$?8GU?$char_traits@G@std@@V?$allocator@G@1@@std@@YA_NABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@0@PBG@Z
	add	esp, 8
	movzx	eax, al
	test	eax, eax
	je	$LN2@UserCmd_Se
; Line 162
	push	OFFSET $SG139299
	lea	ecx, DWORD PTR $T143617[ebp]
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 23		; 00000017H
	push	OFFSET $SG139300
	lea	ecx, DWORD PTR $T143619[ebp]
	call	DWORD PTR __imp_??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@PBD@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 24		; 00000018H
	lea	ecx, DWORD PTR $T143617[ebp]
	push	ecx
	mov	edx, DWORD PTR _iPara$[ebp]
	push	edx
	lea	eax, DWORD PTR $T143618[ebp]
	push	eax
	call	DWORD PTR __imp_?itos@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z
	add	esp, 8
	mov	DWORD PTR tv245[ebp], eax
	mov	ecx, DWORD PTR tv245[ebp]
	mov	DWORD PTR tv393[ebp], ecx
	mov	BYTE PTR __$EHRec$[ebp+8], 25		; 00000019H
	mov	edx, DWORD PTR tv393[ebp]
	push	edx
	lea	eax, DWORD PTR $T143619[ebp]
	push	eax
	lea	ecx, DWORD PTR _scFilePath$[ebp]
	push	ecx
	call	DWORD PTR __imp_?IniWriteW@@YAXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00ABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@2@@Z
	add	esp, 16					; 00000010H
	mov	BYTE PTR __$EHRec$[ebp+8], 24		; 00000018H
	lea	ecx, DWORD PTR $T143618[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 23		; 00000017H
	lea	ecx, DWORD PTR $T143619[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 7
	lea	ecx, DWORD PTR $T143617[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
; Line 163
	sub	esp, 28					; 0000001cH
	mov	ecx, esp
	mov	DWORD PTR $T143620[ebp], esp
	push	OFFSET $SG139302
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	DWORD PTR tv234[ebp], eax
	mov	edx, DWORD PTR tv234[ebp]
	mov	DWORD PTR tv395[ebp], edx
	mov	BYTE PTR __$EHRec$[ebp+8], 26		; 0000001aH
	mov	eax, DWORD PTR _iClientID$[ebp]
	push	eax
	mov	BYTE PTR __$EHRec$[ebp+8], 7
	call	DWORD PTR __imp_?PrintUserCmdText@@YAXIV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ZZ
	add	esp, 32					; 00000020H
; Line 165
	jmp	$LN3@UserCmd_Se
$LN2@UserCmd_Se:
; Line 167
	sub	esp, 28					; 0000001cH
	mov	ecx, esp
	mov	DWORD PTR $T143621[ebp], esp
	push	OFFSET $SG139305
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	DWORD PTR tv409[ebp], eax
	mov	ecx, DWORD PTR tv409[ebp]
	mov	DWORD PTR tv397[ebp], ecx
	mov	BYTE PTR __$EHRec$[ebp+8], 27		; 0000001bH
	mov	edx, DWORD PTR _iClientID$[ebp]
	push	edx
	mov	BYTE PTR __$EHRec$[ebp+8], 7
	call	DWORD PTR __imp_?PrintUserCmdText@@YAXIV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ZZ
	add	esp, 32					; 00000020H
; Line 168
	sub	esp, 28					; 0000001cH
	mov	ecx, esp
	mov	DWORD PTR $T143622[ebp], esp
	push	OFFSET $SG139307
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	DWORD PTR tv411[ebp], eax
	mov	eax, DWORD PTR tv411[ebp]
	mov	DWORD PTR tv399[ebp], eax
	mov	BYTE PTR __$EHRec$[ebp+8], 28		; 0000001cH
	mov	ecx, DWORD PTR _iClientID$[ebp]
	push	ecx
	mov	BYTE PTR __$EHRec$[ebp+8], 7
	call	DWORD PTR __imp_?PrintUserCmdText@@YAXIV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ZZ
	add	esp, 32					; 00000020H
; Line 169
	push	5
	sub	esp, 28					; 0000001cH
	mov	ecx, esp
	mov	DWORD PTR $T143623[ebp], esp
	push	OFFSET $SG139309
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	DWORD PTR tv413[ebp], eax
	mov	edx, DWORD PTR tv413[ebp]
	mov	DWORD PTR tv402[ebp], edx
	mov	BYTE PTR __$EHRec$[ebp+8], 29		; 0000001dH
	mov	eax, DWORD PTR _iClientID$[ebp]
	push	eax
	mov	BYTE PTR __$EHRec$[ebp+8], 7
	call	DWORD PTR __imp_?PrintUserCmdText@@YAXIV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ZZ
	add	esp, 36					; 00000024H
; Line 170
	sub	esp, 28					; 0000001cH
	mov	ecx, esp
	mov	DWORD PTR $T143624[ebp], esp
	push	OFFSET $SG139311
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	DWORD PTR tv415[ebp], eax
	mov	ecx, DWORD PTR tv415[ebp]
	mov	DWORD PTR tv404[ebp], ecx
	mov	BYTE PTR __$EHRec$[ebp+8], 30		; 0000001eH
	mov	edx, DWORD PTR _iClientID$[ebp]
	push	edx
	mov	BYTE PTR __$EHRec$[ebp+8], 7
	call	DWORD PTR __imp_?PrintUserCmdText@@YAXIV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ZZ
	add	esp, 32					; 00000020H
$LN3@UserCmd_Se:
; Line 173
	mov	BYTE PTR $T143625[ebp], 1
	mov	BYTE PTR __$EHRec$[ebp+8], 2
	lea	ecx, DWORD PTR _scFilePath$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 1
	lea	ecx, DWORD PTR _$S3$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	DWORD PTR __$EHRec$[ebp+8], -1
	lea	ecx, DWORD PTR _$S2$[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	al, BYTE PTR $T143625[ebp]
$LN7@UserCmd_Se:
; Line 174
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	esi
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	mov	esp, ebp
	pop	ebp
	ret	0
_TEXT	ENDS
text$x	SEGMENT
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$0:
	lea	ecx, DWORD PTR $T143603[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$1:
	lea	ecx, DWORD PTR _$S2$[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$2:
	lea	ecx, DWORD PTR _$S3$[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$3:
	lea	ecx, DWORD PTR $T143604[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$4:
	lea	ecx, DWORD PTR $T143605[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$5:
	lea	ecx, DWORD PTR _scFilePath$[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$6:
	mov	ecx, DWORD PTR $T143607[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$7:
	lea	ecx, DWORD PTR $T143610[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$8:
	lea	ecx, DWORD PTR $T143612[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$9:
	lea	ecx, DWORD PTR $T143609[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$10:
	lea	ecx, DWORD PTR $T143611[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$11:
	lea	ecx, DWORD PTR $T143613[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$12:
	lea	ecx, DWORD PTR _wscNewMsg$139279[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$13:
	lea	ecx, DWORD PTR $T143615[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$14:
	lea	ecx, DWORD PTR $T143614[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$15:
	mov	ecx, DWORD PTR $T143616[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$16:
	lea	ecx, DWORD PTR $T143617[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$17:
	lea	ecx, DWORD PTR $T143619[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$18:
	lea	ecx, DWORD PTR $T143618[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$19:
	mov	ecx, DWORD PTR $T143620[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$20:
	mov	ecx, DWORD PTR $T143621[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$21:
	mov	ecx, DWORD PTR $T143622[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$22:
	mov	ecx, DWORD PTR $T143623[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z$23:
	mov	ecx, DWORD PTR $T143624[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__ehhandler$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-648]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	ecx, DWORD PTR [edx-4]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
?UserCmd_SetInfo@PlayerInfo@@YA_NIABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@0PBG@Z ENDP ; PlayerInfo::UserCmd_SetInfo
xdata$x	SEGMENT
__unwindtable$?CurrLength@PlayerInfo@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?CurrLength@PlayerInfo@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z$0
	DD	00H
	DD	FLAT:__unwindfunclet$?CurrLength@PlayerInfo@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z$1
	DD	01H
	DD	FLAT:__unwindfunclet$?CurrLength@PlayerInfo@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z$2
	DD	02H
	DD	FLAT:__unwindfunclet$?CurrLength@PlayerInfo@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z$3
__ehfuncinfo$?CurrLength@PlayerInfo@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z DD 019930522H
	DD	04H
	DD	FLAT:__unwindtable$?CurrLength@PlayerInfo@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	00H
; Function compile flags: /Odtp
xdata$x	ENDS
_TEXT	SEGMENT
tv95 = -148						; size = 4
tv68 = -144						; size = 4
tv93 = -140						; size = 4
tv79 = -136						; size = 4
$T143658 = -132						; size = 28
$T143657 = -104						; size = 28
$T143656 = -76						; size = 28
$T143655 = -48						; size = 28
_i$139241 = -20						; size = 4
_iCount$ = -16						; size = 4
__$EHRec$ = -12						; size = 12
_scFilePath$ = 8					; size = 4
?CurrLength@PlayerInfo@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z PROC ; PlayerInfo::CurrLength
; Line 128
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?CurrLength@PlayerInfo@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 136				; 00000088H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
; Line 129
	mov	DWORD PTR _iCount$[ebp], 0
; Line 130
	mov	DWORD PTR _i$139241[ebp], 1
	jmp	SHORT $LN3@CurrLength
$LN2@CurrLength:
	mov	eax, DWORD PTR _i$139241[ebp]
	add	eax, 1
	mov	DWORD PTR _i$139241[ebp], eax
$LN3@CurrLength:
	cmp	DWORD PTR _i$139241[ebp], 5
	jg	$LN1@CurrLength
; Line 132
	push	OFFSET $SG139249
	lea	ecx, DWORD PTR $T143655[ebp]
	call	DWORD PTR __imp_??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@PBG@Z
	mov	DWORD PTR __$EHRec$[ebp+8], 0
	push	OFFSET $SG139250
	lea	ecx, DWORD PTR $T143657[ebp]
	call	DWORD PTR __imp_??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@PBD@Z
	mov	BYTE PTR __$EHRec$[ebp+8], 1
	lea	ecx, DWORD PTR $T143655[ebp]
	push	ecx
	mov	edx, DWORD PTR _i$139241[ebp]
	push	edx
	lea	eax, DWORD PTR $T143656[ebp]
	push	eax
	call	DWORD PTR __imp_?itos@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z
	add	esp, 8
	mov	DWORD PTR tv79[ebp], eax
	mov	ecx, DWORD PTR tv79[ebp]
	mov	DWORD PTR tv93[ebp], ecx
	mov	BYTE PTR __$EHRec$[ebp+8], 2
	mov	edx, DWORD PTR tv93[ebp]
	push	edx
	lea	eax, DWORD PTR $T143657[ebp]
	push	eax
	mov	ecx, DWORD PTR _scFilePath$[ebp]
	push	ecx
	lea	edx, DWORD PTR $T143658[ebp]
	push	edx
	call	?IniGetLongWS@PlayerInfo@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00ABV23@@Z ; PlayerInfo::IniGetLongWS
	add	esp, 20					; 00000014H
	mov	DWORD PTR tv68[ebp], eax
	mov	eax, DWORD PTR tv68[ebp]
	mov	DWORD PTR tv95[ebp], eax
	mov	BYTE PTR __$EHRec$[ebp+8], 3
	mov	ecx, DWORD PTR tv95[ebp]
	call	DWORD PTR __imp_?length@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QBEIXZ
	add	eax, DWORD PTR _iCount$[ebp]
	mov	DWORD PTR _iCount$[ebp], eax
	mov	BYTE PTR __$EHRec$[ebp+8], 2
	lea	ecx, DWORD PTR $T143658[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 1
	lea	ecx, DWORD PTR $T143656[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 0
	lea	ecx, DWORD PTR $T143657[ebp]
	call	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
	mov	DWORD PTR __$EHRec$[ebp+8], -1
	lea	ecx, DWORD PTR $T143655[ebp]
	call	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
; Line 133
	jmp	$LN2@CurrLength
$LN1@CurrLength:
; Line 134
	mov	eax, DWORD PTR _iCount$[ebp]
; Line 135
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	mov	esp, ebp
	pop	ebp
	ret	0
_TEXT	ENDS
text$x	SEGMENT
__unwindfunclet$?CurrLength@PlayerInfo@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z$0:
	lea	ecx, DWORD PTR $T143655[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__unwindfunclet$?CurrLength@PlayerInfo@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z$1:
	lea	ecx, DWORD PTR $T143657[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
__unwindfunclet$?CurrLength@PlayerInfo@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z$2:
	lea	ecx, DWORD PTR $T143656[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ
__unwindfunclet$?CurrLength@PlayerInfo@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z$3:
	lea	ecx, DWORD PTR $T143658[ebp]
	jmp	DWORD PTR __imp_??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@XZ
__ehhandler$?CurrLength@PlayerInfo@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-140]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?CurrLength@PlayerInfo@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
?CurrLength@PlayerInfo@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z ENDP ; PlayerInfo::CurrLength
END
